version: '3'
services:
  app:
    build: .
    tty: true
    command: /bin/bash
#    command: bundle exec rails server -b '0.0.0.0' -p 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
      - NODE_ENV=development
